openapi: 3.0.3
info:
    title: Tuiter
    version: 1.0.0
servers:
    - url: http://localhost:8080/uf2215/api/v2/
paths:
    /roles:
        get:
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Rol'
components:
    schemas:
        Rol:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                nombre:
                    type: string